# Generated by Django 4.1.1 on 2022-12-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaplya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='modwin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Модальное окно',
                'verbose_name_plural': 'Модальное окно',
                'db_table': 'Модальное окно',
            },
        ),
        migrations.RemoveField(
            model_name='kategoriya',
            name='link',
        ),
    ]
